"""LLM calls with automatic DAG integration."""
from .runtime import Runtime
from .shared import (
    _ExecCallState,
    _PERMANENT_ERROR_MARKERS,
    _RETRY_BACKOFF,
    _adapt_tools,
    _assistant_text,
    _build_llm_error,
    _build_pi_context,
    _compute_call_path,
    _current_call_model,
    _current_direct_content,
    _current_effort,
    _current_exec_state,
    _current_loop_opts,
    _current_model_call_budget,
    _current_response_format,
    _current_stream_fn,
    _current_tool_policy,
    _current_tools,
    _default_exec_timeout_s,
    _default_max_retries,
    _exec_system_prompt,
    _fire_on_retry,
    _guess_mime,
    _invoke_adapted_executor,
    _is_permanent_error,
    _log,
    _reap_loop_clients,
    _retry_sleep_seconds,
    _run_and_reap,
    _run_async,
    _situational_prefix,
)
