"""Prompt text for the send_message tool (description shown to the LLM)."""
from __future__ import annotations

DESCRIPTION = (
    "Branch-to-branch communication: deliver a message to an EXISTING "
    "agent, run one turn there, and have its reply "
    "come back to you automatically. An agent's conversation is stored "
    "as a branch in the session DAG; `to` names the branch:\n"
    "\n"
    "  to=\"SID:HEAD\": deliver `message` to that branch and trigger "
    "it to respond. HEAD names the BRANCH (any node on it works, even a "
    "head that has since moved on) — delivery always lands on the "
    "branch's current tip, never forks off history. If the target is "
    "busy running a turn, the message is queued and processed when that "
    "turn ends.\n"
    "  to=\"<branch name>\": address a named branch directly (exact "
    "name, or a unique prefix — see list_agents for names and "
    "addresses).\n"
    "\n"
    "This tool only TALKS to agents that already exist. To CREATE a "
    "new agent (spawn a sub-agent, fork a branch off a node), use the "
    "`agent` tool.\n"
    "\n"
    "To have the target consider other branches, name them in `message` "
    "(e.g. \"read branch SID:HEAD first\") — the target can read them "
    "itself with read_conversation.\n"
    "\n"
    "When you RECEIVE a message from another branch (it starts with "
    "\"[message from SID:HEAD]\"), replying is optional — the message is "
    "already delivered; reply only when you have something substantive "
    "to add, and when unsure, don't reply.\n"
    "\n"
    "Delivery is always asynchronous: this tool returns a delivery id "
    "immediately and you are NOT blocked — keep working. The target's "
    "reply is delivered back to you as a new message automatically when "
    "it finishes."
)
