#!/usr/bin/env node
// Regenerates components/solar-icons/bodies.ts — the inline
// SVG bodies of every Solar icon the app uses, fetched from the Iconify
// API (set `solar`, Solar Icons by 480 Design, CC BY 4.0). The output is
// committed so builds stay offline; rerun this whenever ICONS changes:
//
//   node apps/web/scripts/icons/fetch-solar.mjs
//
// Every icon uses Solar's Bold Duotone style (a filled glyph plus a
// 50 % lighter secondary layer).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ICONS = {
  // composer control row + plus menu
  "tuning-2": "bold-duotone",
  "paperclip": "bold-duotone",
  "toolbox": "bold-duotone",
  "settings-minimalistic": "bold-duotone",
  "global": "bold-duotone",
  "box-minimalistic": "bold-duotone",
  "forward": "bold-duotone",
  "list-arrow-down": "bold-duotone",
  "eye": "bold-duotone",
  "eye-closed": "bold-duotone",
  "dumbbell-large-minimalistic": "bold-duotone",
  "plain-2": "bold-duotone",
  // model / permission badges, question panel
  "chat-round-dots": "bold-duotone",
  "programming": "bold-duotone",
  "shield-check": "bold-duotone",
  // environment row chips + their menus
  "monitor": "bold-duotone",
  "earth": "bold-duotone",
  "pip-2": "bold-duotone",
  "folder-with-files": "bold-duotone",
  "folder-open": "bold-duotone",
  "add-folder": "bold-duotone",
  "danger-triangle": "bold-duotone",
  // menu furniture
  "check-circle": "bold-duotone",
  "close-circle": "bold-duotone",
  "alt-arrow-right": "bold-duotone",
  "alt-arrow-down": "bold-duotone",
  "copy": "bold-duotone",
  // model capability glyphs (agent selector)
  "videocamera": "bold-duotone",
  "lightbulb-bolt": "bold-duotone",
  // per-turn file-change card
  "pen-new-square": "bold-duotone",
  "undo-left-round-square": "bold-duotone",
  "file-text": "bold-duotone",
};

const ids = Object.entries(ICONS).map(([name, style]) => `${name}-${style}`);
const url = `https://api.iconify.design/solar.json?icons=${ids.join(",")}`;
const res = await fetch(url);
if (!res.ok) throw new Error(`Iconify API ${res.status} for ${url}`);
const data = await res.json();
if (data.not_found?.length) throw new Error(`Not in Solar: ${data.not_found.join(", ")}`);

const lines = Object.entries(ICONS).map(([name, style]) => {
  const body = data.icons[`${name}-${style}`]?.body;
  if (!body) throw new Error(`Missing body for ${name}-${style}`);
  return `  /** solar:${name}-${style} */\n  "${name}": ${JSON.stringify(body)},`;
});

const out = `// AUTO-GENERATED by \`apps/web/scripts/icons/fetch-solar.mjs\` — do not hand-edit.
// Solar Icons © 480 Design, CC BY 4.0 — https://github.com/480-Design/Solar-Icon-Set
// Bodies are the Iconify \`solar\` set's 24×24 viewBox contents; every fill
// is currentColor so the glyph takes the surrounding text colour.

export const SOLAR_BODIES = {
${lines.join("\n")}
} as const;

export type SolarIconName = keyof typeof SOLAR_BODIES;
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, "../../components/solar-icons/bodies.ts");
writeFileSync(target, out);
console.log(`wrote ${ids.length} icons → ${target}`);
