#!/usr/bin/env node
// Regenerates components/solar-icons/bodies.ts — the inline
// SVG bodies of every Solar icon the app uses, fetched from the Iconify
// API (set `solar`, Solar Icons by 480 Design, CC BY 4.0). The output is
// committed so builds stay offline; rerun this whenever ICONS changes:
//
//   node apps/web/scripts/icons/fetch-solar.mjs
//
// Every icon uses Solar's Bold Duotone style (a filled glyph plus a
// 50 % lighter secondary layer).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ICONS = {
  // composer control row + plus menu
  "tuning-2": "bold-duotone",
  "paperclip": "bold-duotone",
  "toolbox": "bold-duotone",
  "settings-minimalistic": "bold-duotone",
  "global": "bold-duotone",
  "box-minimalistic": "bold-duotone",
  "forward": "bold-duotone",
  "list-arrow-down": "bold-duotone",
  "eye": "bold-duotone",
  "eye-closed": "bold-duotone",
  "dumbbell-large-minimalistic": "bold-duotone",
  "plain-2": "bold-duotone",
  // model / permission badges, question panel
  "chat-round-dots": "bold-duotone",
  "programming": "bold-duotone",
  "shield-check": "bold-duotone",
  // environment row chips + their menus
  "monitor": "bold-duotone",
  "earth": "bold-duotone",
  "pip-2": "bold-duotone",
  "folder-with-files": "bold-duotone",
  "folder-open": "bold-duotone",
  "add-folder": "bold-duotone",
  "danger-triangle": "bold-duotone",
  // menu furniture
  "check-circle": "bold-duotone",
  "close-circle": "bold-duotone",
  "alt-arrow-right": "bold-duotone",
  "alt-arrow-down": "bold-duotone",
  "copy": "bold-duotone",
  // model capability glyphs (agent selector)
  "videocamera": "bold-duotone",
  "lightbulb-bolt": "bold-duotone",
  // per-turn file-change card
  "pen-new-square": "bold-duotone",
  "file-text": "bold-duotone",
  // per-folder git pill + its menu
  "git-branch": "bold-duotone",
  "git-pull-request": "bold-duotone",
  "add-circle": "bold-duotone",
  "folder-path-connect": "bold-duotone",
  "square-arrow-right-up": "bold-duotone",
};

// A few glyphs come from other Iconify sets where Solar has no good fit;
// they keep their own viewBox. Key → "prefix:name".
//   Font Awesome Free (fa6-solid) © Fonticons, CC BY 4.0 — the file card's
//   undo / review buttons, chosen for their solid weight at 13 px.
const EXTRA = {
  "fa-rotate-left": "fa6-solid:rotate-left",
  "fa-eye": "fa6-solid:eye",
};

const ids = Object.entries(ICONS).map(([name, style]) => `${name}-${style}`);
const url = `https://api.iconify.design/solar.json?icons=${ids.join(",")}`;
const res = await fetch(url);
if (!res.ok) throw new Error(`Iconify API ${res.status} for ${url}`);
const data = await res.json();
if (data.not_found?.length) throw new Error(`Not in Solar: ${data.not_found.join(", ")}`);

const lines = Object.entries(ICONS).map(([name, style]) => {
  const body = data.icons[`${name}-${style}`]?.body;
  if (!body) throw new Error(`Missing body for ${name}-${style}`);
  return `  /** solar:${name}-${style} */\n  "${name}": ${JSON.stringify(body)},`;
});

// Solar glyphs whose artwork sits off-centre in the 24×24 box; the
// viewBox is shifted so the visible shape is centred like its neighbours
// (toolbox spans y 1.25–18.05, so it rode 2.35 units high next to eye
// and lightbulb-bolt in the model picker).
const RECENTRE = {
  toolbox: "0 -2.35 24 24",
};

const viewBoxes = Object.entries(RECENTRE).map(([key, vb]) => `  "${key}": "${vb}",`);
for (const [key, id] of Object.entries(EXTRA)) {
  const [prefix, name] = id.split(":");
  const r = await fetch(`https://api.iconify.design/${prefix}.json?icons=${name}`);
  if (!r.ok) throw new Error(`Iconify API ${r.status} for ${id}`);
  const set = await r.json();
  const icon = set.icons?.[name];
  if (!icon) throw new Error(`Missing ${id}`);
  const w = icon.width ?? set.width ?? 24;
  const h = icon.height ?? set.height ?? 24;
  lines.push(`  /** ${id} */\n  "${key}": ${JSON.stringify(icon.body)},`);
  viewBoxes.push(`  "${key}": "0 0 ${w} ${h}",`);
}

const out = `// AUTO-GENERATED by \`apps/web/scripts/icons/fetch-solar.mjs\` — do not hand-edit.
// Solar Icons © 480 Design, CC BY 4.0 — https://github.com/480-Design/Solar-Icon-Set
// fa-* glyphs: Font Awesome Free © Fonticons, CC BY 4.0 — https://fontawesome.com/license/free
// Bodies are Iconify SVG contents (24×24 unless SOLAR_VIEWBOXES says
// otherwise); every fill is currentColor so the glyph takes the
// surrounding text colour.

export const SOLAR_BODIES = {
${lines.join("\n")}
} as const;

export type SolarIconName = keyof typeof SOLAR_BODIES;

/** viewBox for the non-Solar glyphs, plus Solar glyphs re-centred in their 24×24 box. */
export const SOLAR_VIEWBOXES: Partial<Record<SolarIconName, string>> = {
${viewBoxes.join("\n")}
};
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, "../../components/solar-icons/bodies.ts");
writeFileSync(target, out);
console.log(`wrote ${lines.length} icons → ${target}`);
