"""Prompt text for the agent tool (description shown to the LLM)."""
from __future__ import annotations

DESCRIPTION = (
    "Spawn another agent in the same session and run one turn against "
    "it. Returns the spawned agent's final reply "
    "(run_in_background=false, default) or an execution_id for a "
    "background execution (run_in_background=true). Use job_output with "
    "that id when you need its final reply. This is the ONE tool "
    "that creates new agents; to talk to an agent that already exists, "
    "use send_message instead.\n"
    "\n"
    "Dispatch to an EXISTING agent: pass to='SID:HEAD' or a branch "
    "name (see list_agents) to hand the prompt to that agent as a "
    "tracked task instead of spawning a new one. No branch is created; "
    "the task runs as the target's next turn (queued if it is busy) "
    "and you get an execution_id back immediately — the execution "
    "resource view reports its state, and canonical execution controls "
    "pause, continue, step, steer, fork, retry, or cancel it. The result "
    "also comes back to you automatically. 'to' is mutually exclusive "
    "with start_from, and run_in_background is ignored (always async). "
    "Use to= when the work belongs to an agent that already has the "
    "context; use send_message for conversation that needs no task "
    "tracking.\n"
    "\n"
    "start_from — where the new agent begins, chosen per call:\n"
    "  clean (DEFAULT): the agent starts at a new root seeing ONLY the "
    "prompt — no history, no prior tool results. Use it whenever you "
    "can write a self-contained instruction; pack everything it needs "
    "into the prompt. Cheaper and more focused.\n"
    "  inherit: the agent forks off this turn and sees the whole "
    "conversation chain. Use it only when the sub-task genuinely "
    "depends on the running dialogue. Costs more tokens and carries "
    "noise from prior tool calls.\n"
    "  'SID:MSG_ID': the agent forks off that exact node (any "
    "session), inheriting the chain up to it. Use it to branch a new "
    "line of work from a specific point in the DAG (node addresses "
    "come from list_agents / the chat history).\n"
    "\n"
    "If YOU are a spawned agent, spawning again is refused — do the "
    "work with your own tools. `to=` still works: you may hand work to "
    "an agent that ALREADY exists.\n"
    "\n"
    "The reply lands as a branch in the session DAG, addressable "
    "afterwards by name (see list_agents).\n"
    "\n"
    "Args:\n"
    "  prompt: full instruction. In 'clean' mode this is ALL it sees.\n"
    "  description: short label (1-3 words), used as the branch name.\n"
    "  agent_id: agent profile to run as. Defaults to this session's.\n"
    "  start_from: 'clean' (default), 'inherit', or 'SID:MSG_ID'.\n"
    "  run_in_background: Set to true to run this agent in the "
    "background. You will be notified when it completes and receive "
    "the execution_id for its canonical resource view; use job_output to "
    "retrieve the final reply. Ignored when 'to' "
    "is set.\n"
    "  to: dispatch target — an existing branch as 'SID:HEAD' or a "
    "branch name (see list_agents). Mutually exclusive with start_from.\n"
    "  archive_when_done: true ⇒ archive the spawned branch when its "
    "task ends (after the result came back): it leaves list_agents and "
    "refuses further send_message / agent(to=) deliveries, while its "
    "history stays readable (read_conversation) and forkable "
    "(start_from='SID:MSG_ID'). Default false keeps the agent around for "
    "follow-up questions. Spawn-only — incompatible with 'to'."
)
